
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fjjxznalmpaqotczxxfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqanh6bmFsbXBhcW90Y3p4eGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5MjE1MDIsImV4cCI6MjA3MzQ5NzUwMn0.bCjcKF8-YJ4jz0l_8XdJI0pZpWhxipTwDqdhQYvNnzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
